version: '3.8'

services:
  users-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - NODE_ENV=production
      - PORT=3002
      - SERVICE_NAME=users-service
      - DATABASE_URL=postgresql://postgres.lvacipgdugrcehhdskoe:AivanceDevs2025!@aws-0-us-west-2.pooler.supabase.com:5432/postgres
      - DIRECT_URL=postgresql://postgres.lvacipgdugrcehhdskoe:AivanceDevs2025!@aws-0-us-west-2.pooler.supabase.com:5432/postgres
      - SUPABASE_URL=https://lvacipgdugrcehhdskoe.supabase.co
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2YWNpcGdkdWdyY2VoaGRza29lIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzE1OTU2MywiZXhwIjoyMDc4NzM1NTYzfQ.BIr0T1K37NIIFUSZJVl_FjrpA97D0A_p21AMyDZzo_s
      - LOG_LEVEL=info
      - API_GATEWAY_URL=http://api-gateway:4000
      - DEFAULT_PAGE_SIZE=10
      - MAX_PAGE_SIZE=100
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s